// <auto-generated />
namespace SistemaControleAcesso.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class versao_00101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versao_00101));
        
        string IMigrationMetadata.Id
        {
            get { return "201606070326426_versao_00101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
